### ISSUE TITLE
Fargate SLA?

### ISSUE THREAD

**Issue by mwarkentin** [SummitRoute/aws_research#6]
According to [this blog post](https://aws.amazon.com/blogs/compute/aws-fargate-price-reduction-up-to-50/), fargate has a 99.99% SLA.

> AWS Fargate has achieved SOC, PCI, HIPAA BAA, ISO, MTCS, C5, and ENS High compliance certification, and has a 99.99% SLA.

You don't have a separate row for Fargate, does it make sense to split one out? I don't see the SLA documented on the page you link to in the top piece either.

**Comment by 0xdabbad00** [comment]
Hmm, either they just gave it an SLA and haven't announced it other than that blog post, or it is covered by the EC2 SLA maybe.

As for there being no row, I used botocore to list the names of the services, and so Fargate is subset of the EC2 Container Service (ecs) based on the APIs.  I haven't been sure on how I should name and differentiate the services.  Ex. based on the API names (which I used and modified a bit), or based on the list of services in the web UI, or some other list?

**Comment by mwarkentin** [comment]
Yeah not sure, I was surprised to see the SLA too.

**Comment by mwarkentin** [comment]
@0xdabbad00 found the SLA in the Fargate FAQs too: https://aws.amazon.com/fargate/faqs/

**Comment by 0xdabbad00** [comment]
Looks like it _is_ covered by the EC2 SLA.  I swear I had checked it, by AWS Support direct me to it just now. https://aws.amazon.com/compute/sla/

I updated the table: https://github.com/SummitRoute/aws_research/commit/904c5a539d49b25c4cfe3cd9e83bc09d6e5e0841#diff-579f82aed53fc0979f67c6f7bbd1a296
